version: '3.8'

services:
  db:
    container_name: gsbda
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=root
      - POSTGRES_DB=gsbda
    image: postgres:16
    restart: always
