version: '3.8'

services:
  db:
    container_name: ${DATABASE_NAME}
    ports:
      - '5432:${DATABASE_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    image: postgres:16
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
